#!/usr/bin/env python3
from pathlib import Path
import argparse,json,re,sys
p=argparse.ArgumentParser(); p.add_argument("--root",required=True); p.add_argument("--out",required=True); a=p.parse_args()
root=Path(a.root).resolve(); sys.path.insert(0,str(root/"cqpl/scripts"))
from library_effects_v1 import load_registry,validate_registry_set
reg=load_registry(root/"cqpl/library_models/rust_std_v1.json"); validate_registry_set([reg])
expected={"box_into_raw","box_from_raw","box_leak","mem_forget_owned_box","mem_drop_raw_pointer"}
if reg.status!="candidate": raise SystemExit("rust_std_v1 must be candidate")
items={}
for s in reg.summaries:
    if s.matcher_kind!="producer_evidence_kind" or s.legacy_projection is None: raise SystemExit(f"non-migration summary: {s.summary_id}")
    m=re.fullmatch(r"RustAllocationDispositionEvidenceKind::([A-Za-z_][A-Za-z0-9_]*)",s.provenance["source"])
    if not m: raise SystemExit(f"bad enum provenance: {s.summary_id}")
    if s.matcher_value in items: raise SystemExit("duplicate producer key")
    items[s.matcher_value]=(s,m.group(1))
if set(items)!=expected: raise SystemExit(f"key mismatch: {sorted(items)}")
lines=["// @generated by cqpl/scripts/generate_library_effects_v1_rust.py","// DO NOT EDIT BY HAND.","","use crate::structs::RustAllocationDispositionEvidenceKind;","",
"#[derive(Debug, Clone, Copy, PartialEq, Eq)]","pub enum LegacyTargetVariable { Return, None }","",
"#[derive(Debug, Clone, Copy, PartialEq, Eq)]","pub struct LegacyDispositionProjection {","    pub summary_id: &'static str,","    pub kind: &'static str,","    pub obligation_effect: &'static str,","    pub basis: &'static str,","    pub target_variable: LegacyTargetVariable,","}","",
"pub fn projection_for_producer_evidence(","    evidence: &RustAllocationDispositionEvidenceKind,",") -> LegacyDispositionProjection {","    match evidence {"]
for key in sorted(items):
    s,v=items[key]; q=s.legacy_projection; target="LegacyTargetVariable::Return" if q.target_variable=="return" else "LegacyTargetVariable::None"
    lines += [f"        RustAllocationDispositionEvidenceKind::{v} => LegacyDispositionProjection {{",
              f"            summary_id: {json.dumps(s.summary_id)},",
              f"            kind: {json.dumps(q.allocation_disposition_kind)},",
              f"            obligation_effect: {json.dumps(q.obligation_effect)},",
              f"            basis: {json.dumps(q.basis)},",
              f"            target_variable: {target},","        },"]
lines += ["    }","}",""]
out=Path(a.out); out.parent.mkdir(parents=True,exist_ok=True); out.write_text("\n".join(lines),encoding="utf-8")
print("producer_summaries=",len(items)); print("exhaustive_enum_match=yes"); print("LIBRARY_EFFECTS_V1_RUST_GENERATION: PASS")
