#!/usr/bin/env python3
"""Render full and summary LaTeX tables from cqpl/run_all.sh results.json."""
from __future__ import annotations
import argparse
import json
from pathlib import Path
from collections import Counter


def esc(s: str) -> str:
    repl = {
        "\\": r"\textbackslash{}",
        "&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#",
        "_": r"\_", "{": r"\{", "}": r"\}", "~": r"\textasciitilde{}", "^": r"\textasciicircum{}",
    }
    return "".join(repl.get(c, c) for c in s)


def group(rel: str) -> str:
    if rel.startswith("a-code_c_ffi/"):
        return "C FFI"
    if rel.startswith("a-code_c_to_rust_alloc/"):
        return "C-to-Rust alloc"
    if rel.startswith("a-code_full_rust/"):
        return "Rust"
    if rel.startswith("found vulns/"):
        return "Found vuln"
    if rel.startswith("no_errors_projects/"):
        return "No-error"
    return "Other"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("results", type=Path)
    ap.add_argument("--full", type=Path, required=True)
    ap.add_argument("--summary", type=Path, required=True)
    args = ap.parse_args()
    data = json.loads(args.results.read_text(encoding="utf-8"))
    if data.get("schema_version") != 2:
        raise SystemExit("artifact-evaluation table requires schema-v2 results")
    rows = data["results"]
    queries = ["leak", "double_free", "use_after_free", "allocator_mismatch"]
    labels = {"leak":"Leak", "double_free":"DF", "use_after_free":"UAF-RW", "allocator_mismatch":"AllocMismatch"}

    lines = [
        "% Auto-generated by cqpl/run_all.sh. Do not edit by hand.\n",
        "% Requires: \\usepackage{booktabs,longtable,array}\n",
        "\\begin{longtable}{>{\\raggedright\\arraybackslash}p{0.34\\linewidth} p{0.18\\linewidth} c c c c}\n",
        "\\caption{CQPL schema-v2 results over the active 109-target corpus. \\texttt{ff}=refuted, \\texttt{unk}=not refuted/potential, \\texttt{tt}=established in the abstract model.}\\label{tab:cqpl-ae-corpus}\\\\\n",
        "\\toprule\n",
        "Target & Set & Leak & DF & UAF-RW & AllocMismatch \\\\\n",
        "\\midrule\n",
        "\\endfirsthead\n",
        "\\toprule\n",
        "Target & Set & Leak & DF & UAF-RW & AllocMismatch \\\\\n",
        "\\midrule\n",
        "\\endhead\n",
        "\\midrule\\multicolumn{6}{r}{Continued on next page}\\\\\n",
        "\\endfoot\n",
        "\\bottomrule\n",
        "\\endlastfoot\n",
    ]
    for key, item in sorted(rows.items(), key=lambda kv: kv[1]["relative_path"]):
        if item.get("status") != "complete":
            raise SystemExit(f"non-complete target in AE table input: {key}: {item.get('status')}")
        vals = [item["queries"][q]["result"] for q in queries]
        lines.append(
            f"\\texttt{{{esc(key)}}} & {esc(group(item['relative_path']))} & "
            + " & ".join(r"\texttt{" + esc(v) + "}" for v in vals)
            + " \\\\\n"
        )
    lines.append("\\end{longtable}\n")
    args.full.write_text("".join(lines), encoding="utf-8")

    counts = {q: Counter(item["queries"][q]["result"] for item in rows.values()) for q in queries}
    s = [
        "% Auto-generated by cqpl/run_all.sh.\n",
        "\\begin{table}[t]\n\\centering\n",
        "\\caption{CQPL artifact-evaluation summary for the active corpus.}\\label{tab:cqpl-ae-summary}\n",
        "\\begin{tabular}{lrrr}\n\\toprule\n",
        "Property & \\texttt{ff} & \\texttt{unk} & \\texttt{tt} \\\\\n\\midrule\n",
    ]
    for q in queries:
        c = counts[q]
        s.append(f"{labels[q]} & {c['ff']} & {c['unk']} & {c['tt']} \\\\\n")
    s += [
        "\\bottomrule\n\\end{tabular}\n",
        "\\par\\smallskip\n",
        f"Discovered: {data['discovered_targets']}; active: {data['active_targets']}; "
        f"modeled-complete: {data['modeled_complete']}; skipped: {len(data['skipped_targets'])}.\n",
        "\\end{table}\n",
    ]
    args.summary.write_text("".join(s), encoding="utf-8")
    print(f"AE_LATEX_TABLES: PASS full={args.full} summary={args.summary}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
