// ast.rs
#![allow(dead_code)]
#![allow(unused_imports)]
#![allow(unreachable_patterns)] // momentally for building the ast

use pest::iterators::{Pair, Pairs};
use pest_derive::Parser;
use serde::{Serialize, Deserialize};
use std::collections::HashMap;

/// Parser generated by Pest according to the grammar file 
/// (e.g.: CQPLParser::parse(Rule::file, input) -> parser tree (Pairs<Rule>) storing the rules
#[derive(Parser)]
#[grammar = "cqpl.pest"] // stores CQPL grammar rules
pub struct CQPLParser; 

/// schema for defining a rule
/// e.g:mem_leak.cqpl
/// _____________________
/// # mem_leak          |
/// ## domain: memory   |
/// v: *|*|*            |
///                     |
/// taint_src: *@ alloc |
/// taint_snk: !drop    |
/// ____________________|
/// 
/// Only variable name is case-sensitive
#[derive(Debug, Clone, Serialize, PartialEq, Ord, Eq, PartialOrd, Hash)]
pub struct RuleDef {
    pub name: Vec<String>,          // rule name (e.g.: # memory_leak)
    pub domain: Domain,             // a_mem || taint
    pub variables: Vec<Variable>,   // vars declared within the rule
    pub taint_src: Vec<TaintBlock>, // pre condition
    pub taint_snk: Vec<TaintBlock>, // post condition
}
/// Kind of block
#[derive(Debug, Clone, Serialize, PartialEq, Ord, Eq, PartialOrd,Hash)]
pub enum BlockKind {
    Src,
    Snk,
}
/// Taint block
#[derive(Debug, Clone, Serialize, PartialEq, Ord, Eq, PartialOrd, Hash)]
pub struct TaintBlock {
    pub kind: BlockKind, 
    pub statements: Vec<Statement>,
    pub next_op: Option<SequenceOp>, // corresponds to '|>' in input
}
/// Domain to be specified in the query
#[derive(Debug, Clone, Serialize, PartialEq, Ord, Eq, PartialOrd, Hash)]
pub enum Domain { 
    Memory,     // A_mem lattice (for memory errors)
    General     // T, _|_
} 
/// Sequence between tant src/snk
#[derive(Debug, Clone, Serialize, PartialEq, Ord, Eq, PartialOrd,Hash)]
pub enum SequenceOp {
    Then,
}
/// Variables can be expressed as follow: v_type|qualifier|name   
/// with * for any
#[derive(Debug, Clone, Serialize, PartialEq, Ord, Eq, PartialOrd,Hash)]
pub struct Variable {
    pub v_type: Option<Type>,           // specified var type ||*
    pub qualifier: Option<Qualifier>,   // imm||mut||*
    pub name: Option<VarName>,          // specified || *
}
/// Name of the variable to search in the query can be a soecific name or any
#[derive(Debug, Clone, Serialize, PartialEq, Ord, Eq, PartialOrd,Hash)]
pub enum VarName { 
    Named(String),  // specific var name
    Any             // any variable
}
/// Type of vars to search within the pattern
#[derive(Debug, Clone, Serialize, PartialEq, Ord, Eq, PartialOrd,Hash)]
pub enum Type { Box, Literal, Union, Function, Vec, Enum, Trait, Struct, Reference, Array, String, Tuple, Any }

/// Qualifier associated to variables 
#[derive(Debug, Clone, Serialize, PartialEq, Ord, Eq, PartialOrd,Hash)]
pub enum Qualifier { Imm, Mut, Any }

/// Statements
#[derive(Debug, Clone, Serialize, PartialEq, Ord, Eq, PartialOrd,Hash)]
pub enum Statement {
    Predicate(Predicate),                   // p
    And(Box<Statement>, Box<Statement>),    // &&
    Or(Box<Statement>, Box<Statement>),     // ||
    Not(Box<Statement>),                    // !
    Then(Box<Statement>, Box<Statement>),   // |>
    Wildcard,                               // *
    Quantified {                            // when a statements includd forrall, exists
        quant: Quantifier, 
        var: Option<VarName>,  
        cond: Box<Statement> },
}
/// Quantifiers
#[derive(Debug, Clone, Serialize, PartialEq, Ord, Eq, PartialOrd,Hash)]
pub enum Quantifier { 
    ForAll,     
    Exists      
}
/// Structs, Union, ecc..
#[derive(Debug, Clone, Serialize, PartialEq, Ord, Eq, PartialOrd,Hash)]
pub enum FieldDomain { FieldsOf { typename: String } }

/// Predicates that are supported 
#[derive(Debug, Clone, Serialize, PartialEq, Ord, Eq, PartialOrd,Hash)]
pub enum Predicate {
    Alloc(Option<Term>),
    Drop(Option<Term>),
    Use(Option<Term>),                      // r, w, instanciate
    Read(Option<Term>),
    Write(Option<Term>),
    Assign(Option<Term>),
    Allocator(Language, AllocatorType),        
    InFields(Type),
    Custom(String, Vec<Term>),
    OwnForg(Option<Term>),                  // into_raw
    OwnBack(Option<Term>),                  // from_raw
}

#[derive(Debug, Clone, Serialize, PartialEq, Ord, Eq, PartialOrd,Hash)]
pub enum Language{
    Rust,
    C,
}

/// Type of allocators
#[derive(Debug, Clone, Serialize, PartialEq, Ord, Eq, PartialOrd,Hash)]
pub enum AllocatorType {
    Default,        // global allocator default
    Jemalloc,
    Mimalloc,
    Rpmalloc,
    Snmalloc,
    Weealloc,
    Dlmalloc,
}
/// Composed
#[derive(Debug, Clone, Serialize, PartialEq, Ord, Eq, PartialOrd,Hash)]
pub enum Term { Var(String), FieldAccess { base: String, field: String }, Literal(String) }

 
// FAR VEDERE A LILLO E PIERPAOLO X SEMANTICA
//  (?) DATO CHE DEVO TESTARE GLI OPERATORI: first-order logic model checker with finite domains (possible_values) to decide equivalence
//      - eval_with_env(): evaluates a single formula relative to a binding (env). ENV: var name -> concrete value
//      - semantically_eq(): repeatedly calls eval_with_env() across all environments for all declared variables, ensuring two formulas are the same.
// Define a type alias for the environment: a map from variable names (String) to their concrete values (String)
// This environment holds the current variable bindings during evaluation
pub type Env = HashMap<String, String>; // var name -> concrete value

/// Kind of statement, depending if its is declred on a src or snk
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum StmtKind {
    Src,
    Snk,
    Other,
}

impl Statement {
    /// Evaluate the formula under the environment env
    /// It's generic over <F>: a function type used to interpret the predicates
    pub fn eval_with_env<F>(
        &self,                              // current stmnt to be evaluated
        f: &F,                              // external function. It evauates if a predicate is T || F under the env (PREDICATE EVALUATOR)
        env: &Env,                          // env: variables -> values
        variables: &[Variable],             // vars declared within the rule
        possible_values: &[String],         // concrete values that each var can assume (Domain of each value, finite set)
    ) -> bool
    // the eval_with_env<F> type will only be defined for types F that satisfies the constraint:
    where F: Fn(&Predicate, &Env) -> bool{    
        // define generic internal recursive function that traverse the Statement tree recursively
        fn rec<F>(
            stmt: &Statement,               // subtree to be evaluated
            f: &F,                          // predicate evaluator    
            env_mut: &mut Env,              // mutable env -> quantifiers can bind/unbind vars
            _variables: &[Variable],        // declared var
            possible_values: &[String],     // domain
            anon_counter: &mut usize,       // global, incrementing ID generator for fresh variable names used when quantifiers bind anonymous variables (__quant_0, __quant_1, ...) 
                                            // to generate unique names for anonymous vars when using quantifiers (forall and exists) when the user not explicitly name a variable   
                                            // e.g.: \forall *. alloc(*) -> no real variable name for the bound var. Internally, need to bind each candidate value into the environment (Env) with some key.
                                            // To do, generate a fresh unique variable name: First anonymous -> __quant_0; Second anonymous -> __quant_1
        ) -> bool
        where F: Fn(&Predicate, &Env) -> bool {
            // pattern matching on Statment predicate kind
            match stmt {
                Statement::Predicate(p) => { f(p, env_mut) }    // delegate predicate evaluation to external function f
                Statement::Not(inner) => !rec(inner, f, env_mut, _variables, possible_values, anon_counter),   // negatetion, flip the result
                Statement::And(lhs, rhs) => { // AND
                    rec(lhs, f, env_mut, _variables, possible_values, anon_counter)
                        && rec(rhs, f, env_mut, _variables, possible_values, anon_counter)}
                Statement::Or(lhs, rhs) => { // OR
                    rec(lhs, f, env_mut, _variables, possible_values, anon_counter)
                        || rec(rhs, f, env_mut, _variables, possible_values, anon_counter)}
                Statement::Then(lhs, rhs) => {
                    // semantics: if lhs true then rhs must be true; if lhs false, the whole Then is false
                    if rec(lhs, f, env_mut, _variables, possible_values, anon_counter) {
                        rec(rhs, f, env_mut, _variables, possible_values, anon_counter)
                    } else {
                        false
                    }
                }
                Statement::Wildcard => true, // always true
                Statement::Quantified { quant, var, cond } => {
                    match quant {
                        Quantifier::ForAll => {
                            // ForAll: for every possible value, cond must hold
                            possible_values.iter().all(|val| {
                                // choose key: named var -> use name, otherwise generate fresh anon key
                                let key = match var {
                                    Some(VarName::Named(name)) => name.clone(),
                                    Some(VarName::Any) | None => {
                                        // generate unique anon key (will be removed after eval)
                                        let k = format!("__quant_{}", *anon_counter);
                                        *anon_counter += 1;
                                        k
                                    }
                                };
                                // save old binding (if any)
                                let old = env_mut.insert(key.clone(), val.clone());
                                // evaluate condition under this new binding
                                let res = rec(cond, f, env_mut, _variables, possible_values, anon_counter);
                                // restore old binding
                                match old {
                                    Some(prev) => { env_mut.insert(key.clone(), prev); }
                                    None => { env_mut.remove(&key); }
                                }
                                res
                            })
                        }
                        Quantifier::Exists => {
                            // Exists: there exists a value such that cond holds
                            possible_values.iter().any(|val| {
                                let key = match var {
                                    Some(VarName::Named(name)) => name.clone(),
                                    Some(VarName::Any) | None => {
                                        let k = format!("__quant_{}", *anon_counter);
                                        *anon_counter += 1;
                                        k
                                    }
                                };
                                let old = env_mut.insert(key.clone(), val.clone());
                                let res = rec(cond, f, env_mut, _variables, possible_values, anon_counter);
                                match old {
                                    Some(prev) => { env_mut.insert(key.clone(), prev); }
                                    None => { env_mut.remove(&key); }
                                }
                                res
                            })
                        }
                    }
                }
                Statement::Or(_, _) | Statement::And(_, _) | Statement::Not(_) | Statement::Then(_, _) | Statement::Predicate(_) | Statement::Wildcard | Statement::Quantified { .. } => {
                // match is exhaustive above, this branch is unreachable but the compiler shuts up
                unreachable!()
                }
            }
        }
        // inizializza env mutabile a partire dall'env di input (work on a copy to avoid side-effects)
        let mut env_clone = env.clone();
        let mut anon_counter: usize = 0;
        rec(self, f, &mut env_clone, variables, possible_values, &mut anon_counter)
    }
}

/// check if 2 statements are semanticalle eq on all over the assignments of vars declared using possible_values
pub fn semantically_eq<F>(
    stmt1: &Statement,
    stmt2: &Statement,
    _preds: &[Predicate],               
    variables: &[Variable],
    possible_values: &[String],
    eval_fn: &F,
) -> bool
where F: Fn(&Predicate, &Env) -> bool {
    // helper ricorsivo: remaining_vars è la porzione di var rimanenti da instanziare
    fn helper<F>(
        stmt1: &Statement,
        stmt2: &Statement,
        env: &mut Env,
        remaining_vars: &[Variable],
        declared_vars: &[Variable],       // passare le var dichiarate a eval_with_env
        possible_values: &[String],
        eval_fn: &F,
        anon_idx: usize,                  // indice per var anonime (genera __any_i)
    ) -> bool
    where F: Fn(&Predicate, &Env) -> bool {
        if remaining_vars.is_empty() {
            // tutte le variabili sono assegnate: valuta i due statement nello stesso env
            return stmt1.eval_with_env(eval_fn, env, declared_vars, possible_values)
                == stmt2.eval_with_env(eval_fn, env, declared_vars, possible_values);
        }
        let first_var = &remaining_vars[0];
        let rest_vars = &remaining_vars[1..];
        // chiave per la current var
        let key_base = match &first_var.name {
            Some(VarName::Named(n)) => n.clone(),
            Some(VarName::Any) | None => format!("__any_{}", anon_idx),
        };
        // per ogni valore possibile
        for val in possible_values.iter() {
            // inserimento in-place e salvo vecchio valore
            let old = env.insert(key_base.clone(), val.clone());

            // se la chiamata ricorsiva fallisce per una qualche assegnazione -> false
            if !helper(
                stmt1,
                stmt2,
                env,
                rest_vars,
                declared_vars,
                possible_values,
                eval_fn,
                anon_idx + 1, // increment anon_idx quando consumo una var (anonima o no)
            ) {
                // ripristina env prima di tornare
                match old {
                    Some(prev) => {
                        env.insert(key_base.clone(), prev);
                    }
                    None => {
                        env.remove(&key_base);
                    }
                }
                return false;
            }
            // ripristino env per provare il prossimo valore
            match old {
                Some(prev) => {
                    env.insert(key_base.clone(), prev);
                }
                None => {
                    env.remove(&key_base);
                }
            }
        }
        // tutte le assegnazioni per questa variabile hanno passato il test
        true
    }

    let mut env = Env::new();
    helper(
        stmt1,
        stmt2,
        &mut env,
        variables,
        variables,          // declared_vars = variables
        possible_values,
        eval_fn,
        0,                  // anon_idx parte da 0
    )
}

/// Function to validead kind of taint: src or snk for the |> (because is allowed only on more src or more snk)
pub fn validate_rule(rule: &RuleDef) {
    // check taint_src
    for (i, block) in rule.taint_src.iter().enumerate() {
        if let Some(SequenceOp::Then) = block.next_op {
            if let Some(next_block) = rule.taint_src.get(i+1) {
                if block.kind != next_block.kind {
                    panic!("Invalid sequence: {:?} |> {:?}", block.kind, next_block.kind);
                }
            }
        }
    }
    // check taint_snk
    for (i, block) in rule.taint_snk.iter().enumerate() {
        if let Some(SequenceOp::Then) = block.next_op {
            if let Some(next_block) = rule.taint_snk.get(i+1) {
                if block.kind != next_block.kind {
                    panic!("Invalid sequence: {:?} |> {:?}", block.kind, next_block.kind);
                }
            }
        }
    }
}

/// AST Builder
/// Input: result of the parser
/// recursively visits all pairs of the tree
/// Output: for each rule_item (i.e.: a rule) returns a vector of rule definition
pub fn build_ast(pairs: Pairs<Rule>) -> Vec<RuleDef> {
    let mut rules = Vec::new();
    for pair in pairs {
        match pair.as_rule() {
            Rule::file => rules.extend(build_ast(pair.into_inner())),
            Rule::rule_item => {
                let mut name = Vec::new();
                let mut domain = Domain::General;
                let mut variables = Vec::new();
                let mut taint_src = Vec::new();
                let mut taint_snk = Vec::new();

                for inner in pair.into_inner() {
                    match inner.as_rule() {
                        Rule::rule_header => name.push(inner.as_str().trim().to_string()),
                        Rule::var_decl => {
                            if let Some((_, pattern)) = inner.as_str().trim().split_once(':') {
                                let slots: Vec<&str> = pattern.trim().split('|').collect();
                                let v_type = match slots.get(0).map(|s| s.to_lowercase()) {
                                    Some(ref s) if *s == "box" => Some(Type::Box),
                                    Some(ref s) if *s == "literal" => Some(Type::Literal),
                                    Some(ref s) if *s == "union" => Some(Type::Union),
                                    Some(ref s) if *s == "function" => Some(Type::Function),
                                    Some(ref s) if *s == "vec" || *s == "vector" => Some(Type::Vec),
                                    Some(ref s) if *s == "enum" => Some(Type::Enum),
                                    Some(ref s) if *s == "trait" => Some(Type::Trait),
                                    Some(ref s) if *s == "struct" => Some(Type::Struct),
                                    Some(ref s) if *s == "reference" => Some(Type::Reference),
                                    Some(ref s) if *s == "array" || *s == "arr" => Some(Type::Array),
                                    Some(ref s) if *s == "string" => Some(Type::String),
                                    Some(ref s) if *s == "tuple" || *s == "tup" => Some(Type::Tuple),
                                    Some(ref s) if *s == "*" => Some(Type::Any),
                                    None => Some(Type::Any),
                                    _ => Some(Type::Any),
                                };
                                let qualifier = match slots.get(1).map(|s| s.to_lowercase()) {
                                    Some(ref s) if *s == "imm" => Some(Qualifier::Imm),
                                    Some(ref s) if *s == "mut" => Some(Qualifier::Mut),
                                    Some(ref s) if *s == "*" => Some(Qualifier::Any),
                                    None => Some(Qualifier::Any),
                                    _ => Some(Qualifier::Any),
                                };
                                let var_name = match slots.get(2).map(|s| *s) {
                                    Some("*") | None => VarName::Any,
                                    Some(name) => VarName::Named(name.to_string()),
                                };
                                variables.push(Variable {
                                    name: Some(var_name),
                                    v_type,
                                    qualifier,
                                });
                            }
                        }
                        Rule::domain_decl => {
                            domain = if inner.as_str().to_lowercase().contains("memory") {
                                Domain::Memory
                            } else {
                                Domain::General
                            }
                        }
                        Rule::taint_src_decl => {
                            let mut inner_pairs = inner.into_inner().peekable();
                            while let Some(stmt_block) = inner_pairs.next() {
                                let statements = parse_ordered_statements(stmt_block);

                                let next_op = if inner_pairs.peek().is_some() {
                                    Some(SequenceOp::Then)
                                } else {
                                    None
                                };

                                taint_src.push(TaintBlock {
                                    statements,
                                    next_op,
                                    kind: BlockKind::Src,
                                });
                            }
                        }
                        Rule::taint_snk_decl => {
                            let mut inner_pairs = inner.into_inner().peekable();
                            while let Some(stmt_block) = inner_pairs.next() {
                                let statements = parse_ordered_statements(stmt_block);

                                let next_op = if inner_pairs.peek().is_some() {
                                    Some(SequenceOp::Then)
                                } else {
                                    None
                                };

                                taint_snk.push(TaintBlock {
                                    statements,
                                    next_op,
                                    kind: BlockKind::Snk,
                                });
                            }
                        }
                        _ => {}
                    }
                }
                if !name.is_empty() {
                    let rule = RuleDef {
                        name,
                        domain,
                        variables,
                        taint_src,
                        taint_snk,
                    };
                    validate_rule(&rule);
                    rules.push(rule);
                }
            }
            _ => {}
        }
    }
    rules
}

pub fn parse_ordered_statements(pair: Pair<Rule>) -> Vec<Statement> {
    pair.into_inner().map(|stmt| parse_statement(stmt)).collect()
}
/// parsing
pub fn parse_statement(pair: Pair<Rule>) -> Statement {
    match pair.as_rule() {
        // handle sequence_expr (if present in the grammar)
        Rule::sequence_expr => {
            let mut inner = pair.into_inner();
            let first = parse_statement(inner.next().unwrap());
            inner.fold(first, |acc, stmt| {
                Statement::Then(Box::new(acc), Box::new(parse_statement(stmt)))
            })
        }
        Rule::order_expr => {
            let mut inner = pair.into_inner();
            let first = parse_statement(inner.next().unwrap());
            inner.fold(first, |acc, stmt| {
                let rhs = parse_statement(stmt);
                Statement::Then(Box::new(acc), Box::new(rhs))
            })
        }
        // primary: container node having only one significant child (predicate, quant_expr, wildcard, paren_expr)
        Rule::primary => {
            parse_statement(pair.into_inner().next().unwrap())
        }
        // if pair is predicate -> construct a Statement::Predicate
        Rule::predicate => Statement::Predicate(parse_predicate(pair)),
        // wildcard * -> Statement::Wildcard
        Rule::wildcard => Statement::Wildcard,
        // not_expr: may have more ! in the head of declartion
        Rule::not_expr => {
            let text = pair.as_str().to_string();
            let mut inner = pair.into_inner();
            let mut stmt = parse_statement(inner.next().unwrap());
            for _ in text.chars().take_while(|c| *c == '!') {
                stmt = Statement::Not(Box::new(stmt));
            }
            stmt
        }
        Rule::quant_expr => {
            // render inner as iterator so we can inspect following tokens
            let quantifier_input_str = pair.as_str().trim().to_string();
            let mut inner = pair.into_inner().peekable();

            let quantifier = if quantifier_input_str.starts_with("\\forall") {
                Quantifier::ForAll
            } else if quantifier_input_str.starts_with("\\exists") {
                Quantifier::Exists
            } else {
                panic!("Invalid quantifier. Supported: \\forall or \\exists");
            };
            // primi token: il bound_var (obbligatorio nelle alternative della grammatica)
            let first = inner.next().expect("quant_expr must have at least one child");
            let bound_name = first.as_str().to_string();
            let bound_lower = bound_name.to_lowercase();

            // keywords di predicato da interpretare come "no-var" quando non c'è altro come armomento a
            let pred_keywords = ["alloc", "drop", "use", "read", "write", "assign", "allocator"];
            // se non ci sono altri token dopo il bound
            if inner.peek().is_none() {
                // caso: \forall alloc -> var = Any, cond = Predicate(alloc())
                if pred_keywords.contains(&bound_lower.as_str()) {
                    // costruisco il predicato senza argomenti
                    let pred = match bound_lower.as_str() {
                        "alloc" => Predicate::Alloc(None),
                        "drop" => Predicate::Drop(None),
                        "use" => Predicate::Use(None),
                        "read" => Predicate::Read(None),
                        "write" => Predicate::Write(None),
                        "assign" => Predicate::Assign(None),
                        "allocator" => panic!("allocator predicate without args is invalid"),
                        _ => unreachable!(),
                    };
                    Statement::Quantified {
                        quant: quantifier,
                        var: Some(VarName::Any),
                        cond: Box::new(Statement::Predicate(pred)),
                    }
                } else {
                    // nessun corpo: \forall x  -> var x, cond = Wildcard
                    Statement::Quantified {
                        quant: quantifier,
                        var: Some(VarName::Named(bound_name)),
                        cond: Box::new(Statement::Wildcard),
                    }
                }
            } else {
                // c'è almeno un token dopo il bound_var => interpreto i casi possibili
                // next può essere: type_access (in ... fields), predicate, oppure logic_expr / altro
                let next = inner.next().unwrap();

                match next.as_rule() {
                    Rule::type_access => {
                        // tipo come Vec.fields
                        let txt = next.as_str();
                        let (ty_str, suffix) = txt.split_once('.').expect("type_access must be in the format Type.fields");
                        if suffix != "fields" { panic!("error in declaring type_access: {}", txt); }
                        let ty = match ty_str.to_lowercase().as_str() {
                            "vec" => Type::Vec,
                            "struct" => Type::Struct,
                            "union" => Type::Union,
                            "array" => Type::Array,
                            "tuple" => Type::Tuple,
                            other => panic!("Type '{}' is not allowed for .fields", other),
                        };
                        // se dopo il type_access c'è un predicato (opzionale nella grammatica)
                        let mut cond_parts: Vec<Statement> = vec![Statement::Predicate(Predicate::InFields(ty))];
                        if let Some(maybe_pred) = inner.next() {
                            if maybe_pred.as_rule() == Rule::predicate {
                                cond_parts.push(Statement::Predicate(parse_predicate(maybe_pred)));
                            } else {
                                // se è altro, parse as stmnt
                                cond_parts.push(parse_statement(maybe_pred));
                            }
                        }
                        let cond_stmt = cond_parts.into_iter().reduce(|a, b| Statement::And(Box::new(a), Box::new(b))).unwrap_or(Statement::Wildcard);
                        Statement::Quantified {
                            quant: quantifier,
                            var: Some(VarName::Named(bound_name)),
                            cond: Box::new(cond_stmt),
                        }
                    }
                    Rule::predicate => {
                        // case  \forall x. drop   OR  \forall x. alloc(x) produce predicate 
                        let pred = parse_predicate(next);
                        Statement::Quantified {
                            quant: quantifier,
                            var: Some(VarName::Named(bound_name)),
                            cond: Box::new(Statement::Predicate(pred)),
                        }
                    }
                    // se è un intero logic_expr / paren_expr / altro, recursively parsing
                    _ => {
                        let cond_stmt = parse_statement(next);
                        Statement::Quantified {
                            quant: quantifier,
                            var: Some(VarName::Named(bound_name)),
                            cond: Box::new(cond_stmt),
                        }
                    }
                }
            }
        }
        Rule::and_expr => {
            let mut inner = pair.into_inner();
            let first = parse_statement(inner.next().unwrap());
            inner.fold(first, |acc, stmt| {
                Statement::And(Box::new(acc), Box::new(parse_statement(stmt)))
            })
        }
        Rule::or_expr => {
            let mut inner = pair.into_inner();
            let first = parse_statement(inner.next().unwrap());
            inner.fold(first, |acc, stmt| {
                Statement::Or(Box::new(acc), Box::new(parse_statement(stmt)))
            })
        }
        Rule::paren_expr | Rule::logic_expr  => {
            parse_statement(pair.into_inner().next().unwrap())
        }
        _ => panic!("Unexpected rule in parse_statement: {:?}", pair.as_rule()),
    }
}

// Parse the predicate
pub fn parse_predicate(pair: Pair<Rule>) -> Predicate {
    // get raw string of the predicate and trim whitespace
    let txt = pair.as_str().trim();
    // separate predicate name and optional args inside parentheses
    // return a tuple: (name: String, args: Vec<Term>)
    let (name, args): (String, Vec<Term>) = if let Some(idx) = txt.find('(') {
        // if there is a ( in the predicate, extract the name before it
        let name = txt[..idx].to_lowercase(); // handles case insensitive predicate names
        // extract the string inside parentheses (ars)
        let args_str = &txt[idx + 1..txt.len() - 1]; // remove closing parenthesis )
        // parse arguments
        let args_vec = if args_str.trim().is_empty() {
            // EMPTY PARENTHESIS handling, e.g., ALLOC()
            vec![]
        } else {
            args_str
                .split(',') // handle multiple arguments separated by ,
                .map(|s| {
                    let s = s.trim();
                    //  FIELD ACCESS, e.g., x.y
                    if let Some(dot_idx) = s.find('.') {
                        let base = &s[..dot_idx];
                        let field = &s[dot_idx + 1..];
                        Term::FieldAccess {
                            base: base.to_string(),
                            field: field.to_string(),
                        }
                    } else {
                        // VAR ARGUMENT (simple case), e.g., x
                        Term::Var(s.to_string())
                    }
                })
                .collect()
        };
        (name, args_vec)
    } else {
        // PREDICATE WITHOUT (), e.g., ALLOC
        (txt.to_lowercase(), vec![])
    };
    // map the predicate name to the corresponding enum variant
    // uf there is an arg, pass the first one; if none, pass None
    match name.as_str() {
        "alloc"      => Predicate::Alloc(args.get(0).cloned()),
        "drop"       => Predicate::Drop(args.get(0).cloned()),
        "use"        => Predicate::Use(args.get(0).cloned()),
        "read"       => Predicate::Read(args.get(0).cloned()),
        "write"      => Predicate::Write(args.get(0).cloned()),
        "assign"     => Predicate::Assign(args.get(0).cloned()),
        "own_forg" | "ownforg" => Predicate::OwnForg(args.get(0).cloned()), // to be tested
        "own_back" | "ownback" => Predicate::OwnBack(args.get(0).cloned()),  // to be tested
        "allocator"  => {
            // expects exactly 2 args: language and allocator type
            if args.len() != 2 {
                panic!("Allocator predicate requires 2 arguments: language and allocator type, got {}", args.len());
            }// parse 1st argt: Language
            let lang = match &args[0] {
                Term::Var(s) => match s.to_lowercase().as_str() {
                    "rust" => Language::Rust,
                    "c" => Language::C,
                    other => panic!("Unknown language '{}'", other),
                },
                _ => panic!("First argument of allocator must be a language"),
            };// parse 2nd arg: AllocatorType
            let alloc_type = match &args[1] {
                Term::Var(s) => match s.to_lowercase().as_str() {
                    "default" => AllocatorType::Default,
                    "jemalloc" => AllocatorType::Jemalloc,
                    "mimalloc" => AllocatorType::Mimalloc,
                    "rpmalloc" => AllocatorType::Rpmalloc,
                    "snmalloc" => AllocatorType::Snmalloc,
                    "weealloc" => AllocatorType::Weealloc,
                    "dlmalloc" => AllocatorType::Dlmalloc,
                    other => panic!("Unknown allocator type '{}'", other),
                },
                _ => panic!("Second argument of allocator must be an allocator type"),
            };
            Predicate::Allocator(lang, alloc_type)
        }
        _ => panic!("Unknown predicate: {}", name), // // no Custom predicates; UNKNOWN PREDICATES WILL panic
    }
}






/* 
impl Statement {
    // Evaluate the formula under the environment env
    pub fn eval_with_env<F>(
        &self,                      // stmnt to be evaluated
        f: &F,                      // external function. It will tell if a predicate is T || F under the env
        env: &Env,                  // env: variables -> values
        variables: &[Variable],     // vars declared within the rule
        possible_values: &[String], // concrete values that each var can assume
    ) -> bool
    where
        F: Fn(&Predicate, &Env) -> bool,
    {
        // internal recursive function working in-place on env_mut, acts on tree structure of statements
        fn rec<F>(
            stmt: &Statement,
            f: &F,
            env_mut: &mut Env,
            variables: &[Variable],
            possible_values: &[String],
            anon_counter: &mut usize,
        ) -> bool
        where
            F: Fn(&Predicate, &Env) -> bool,
        {
            match stmt {
                Statement::Predicate(p) => f(p, env_mut),                                                   // check to f(p,env) if p is true under the current environment env
                Statement::Not(inner) => !rec(inner, f, env_mut, variables, possible_values, anon_counter), // evaluate the inner stmnt and negates it
                Statement::And(lhs, rhs) => {                                                               // both stamnts must be T
                    rec(lhs, f, env_mut, variables, possible_values, anon_counter)  && rec(rhs, f, env_mut, variables, possible_values, anon_counter)
                }
                Statement::Or(lhs, rhs) => {                                                                // 1 stmnt must be T
                    rec(lhs, f, env_mut, variables, possible_values, anon_counter) || rec(rhs, f, env_mut, variables, possible_values, anon_counter)
                }
                Statement::Then(lhs, rhs) => {                                                              // |> then operator as sequence
                // pif lhs is T under the env, then rhs must be T
                if rec(lhs, f, env_mut, variables, possible_values, anon_counter) {     
                    rec(rhs, f, env_mut, variables, possible_values, anon_counter)
                } else { //se lhs if F, the whole formula is false
                    false
                }
            }
                Statement::Wildcard => true,            
                                                           // * always T 
/* 
            Statement::Quantified { quant, var, cond } => {
    match quant {
        Quantifier::ForAll => {
            possible_values.iter().all(|val| {
                let key = match var {
                    Some(VarName::Named(name)) => name.clone(),
                    Some(VarName::Any) | None => {
                        let k = format!("__quant_{}", *anon_counter);
                        *anon_counter += 1;
                        k
                    }
                };

                // salva valore precedente (se c'era)
                let old = env_mut.insert(key.clone(), val.clone());

                let res = rec(cond, f, env_mut, variables, possible_values, anon_counter);

                // ripristina
                match old {
                    Some(prev) => { env_mut.insert(key.clone(), prev); }
                    None => { env_mut.remove(&key); }
                }

                res
            })
        }
        Quantifier::Exists => {
            possible_values.iter().any(|val| {
                let key = match var {
                    Some(VarName::Named(name)) => name.clone(),
                    Some(VarName::Any) | None => {
                        let k = format!("__quant_{}", *anon_counter);
                        *anon_counter += 1;
                        k
                    }
                };

                let old = env_mut.insert(key.clone(), val.clone());
                let res = rec(cond, f, env_mut, variables, possible_values, anon_counter);

                match old {
                    Some(prev) => { env_mut.insert(key.clone(), prev); }
                    None => { env_mut.remove(&key); }
                }

                res
            })
        }
    }
}*/
       

/* 
Statement::Quantified { quant, var, cond } => {
    match quant {
        Quantifier::ForAll => {
            possible_values.iter().all(|val| {
                // ogni iterazione parte da una copia pulita
                let mut env_local = env_mut.clone();

                // nome della variabile (se Named, usa quello; altrimenti genera chiave unica)
                let key = match var {
                    Some(VarName::Named(name)) => name.clone(),
                    Some(VarName::Any) | None => {
                        let k = format!("__quant_{}", *anon_counter);
                        *anon_counter += 1;
                        k
                    }
                };

                // assegna la variabile all'ambiente locale
                env_local.insert(key, val.clone());

                // valuta la condizione con env locale
                rec(cond, f, &mut env_local, variables, possible_values, anon_counter)
            })
        }
        Quantifier::Exists => {
            possible_values.iter().any(|val| {
                let mut env_local = env_mut.clone();

                let key = match var {
                    Some(VarName::Named(name)) => name.clone(),
                    Some(VarName::Any) | None => {
                        let k = format!("__quant_{}", *anon_counter);
                        *anon_counter += 1;
                        k
                    }
                };

                env_local.insert(key, val.clone());

                rec(cond, f, &mut env_local, variables, possible_values, anon_counter)
            })
        }
    }
}
*/

     
                Statement::Quantified { quant, var, cond } => {
                    // Handle quantifiers
                    // - se Named(name): use proprio name
                    // - altrimenti (Any/None): genero una chiave unica __quant_i
                    match quant {
                        Quantifier::ForAll => { // all elements must be satisfy
                            possible_values.iter().all(|val| {
                                // genera chiave unica
                                let key = match var {
                                    Some(VarName::Named(name)) => name.clone(),
                                    Some(VarName::Any) | None => {
                                        let k = format!("__quant_{}", *anon_counter);
                                        *anon_counter += 1;
                                        k
                                    }
                                };
                                // backtracking in-place: salve and insert
                                let old = env_mut.insert(key.clone(), val.clone());
                                // valuta la condizione
                                let res = rec(cond, f, env_mut, variables, possible_values, anon_counter);
                                // ripristina env (old può essere Some(prev) o None)
                                match old {
                                    Some(prev) => { env_mut.insert(key.clone(), prev); }
                                    None => { env_mut.remove(&key); }
                                }
                                res
                            })
                        }
                        Quantifier::Exists => { // at least one must satisfy
                            possible_values.iter().any(|val| {
                                let key = match var {
                                    Some(VarName::Named(name)) => name.clone(),
                                    Some(VarName::Any) | None => {
                                        let k = format!("__quant_{}", *anon_counter);
                                        *anon_counter += 1;
                                        k
                                    }
                                };
                                let old = env_mut.insert(key.clone(), val.clone());
                                let res = rec(cond, f, env_mut, variables, possible_values, anon_counter);
                                match old {
                                    Some(prev) => { env_mut.insert(key.clone(), prev); }
                                    None => { env_mut.remove(&key); }
                                }
                                res
                            })
                        }
                    }
                }


            }
        }
        // copia mutabile dell'env di partenza ma non clono dentro i loop (backtracking in-place)
        let mut env_clone = env.clone();
        let mut anon_counter: usize = 0;
        rec(self, f, &mut env_clone, variables, possible_values, &mut anon_counter)
    }
}
*/









/* 
impl Statement {
    /// Evaluate a logical formula under an environment.
    /// plug in variable bindings, then check the formula truth using f as a semantics oracle for base predicates
    pub fn eval_with_env<F>(
        &self, 
        f: &F,     // a callback that says whether a Predicate (eg alloc(x), drop(y)...) is true given the current env
        env: &Env, // a map from variable names to concrete values, eg: { "x" -> "ptr1" }
        variables: &[Variable], // declared variables in scope (at the beginning)
        possible_values: &Vec<String>  //vall possible concrete values those variables could take
        )-> bool
    where
        F: Fn(&Predicate, &Env) -> bool,
    {
        match self {
            Statement::Predicate(p) => f(p, env),   // delegates to f(p, env)
            Statement::Not(inner) => !inner.eval_with_env(f, env, variables, possible_values), // negates inner truth
            Statement::And(lhs, rhs) => lhs.eval_with_env(f, env, variables, possible_values) && rhs.eval_with_env(f, env, variables, possible_values), // both must be true
            Statement::Or(lhs, rhs) => lhs.eval_with_env(f, env, variables, possible_values) || rhs.eval_with_env(f, env, variables, possible_values),  // either must be true
            Statement::Then(lhs, rhs) => lhs.eval_with_env(f, env, variables, possible_values) && rhs.eval_with_env(f, env, variables, possible_values), // NB: for the moment same as And(lhs, rhs)
            Statement::Wildcard => true, // always true
            Statement::Quantified { quant, var, cond } => {  // loops over all possible_values, binds them to the quantified var (x, u, etc.) in a fresh copy of env, and evaluates the condition
                let var_name = match var {
                    Some(VarName::Named(name)) => name,
                    Some(VarName::Any) | None => "__any",
                };
                match quant {
                    Quantifier::ForAll => {
                        possible_values.iter().all(|val| {
                            let mut env_new = env.clone();
                            env_new.insert(var_name.to_string(), val.clone());
                            cond.eval_with_env(f, &env_new, variables, possible_values)
                        })
                    }
                    Quantifier::Exists => {
                        possible_values.iter().any(|val| {
                            let mut env_new = env.clone();
                            env_new.insert(var_name.to_string(), val.clone());
                            cond.eval_with_env(f, &env_new, variables, possible_values)
                        })
                    }
                }
            }
        }
    }
}*/


/* 
pub fn semantically_eq<F>(
    stmt1: &Statement, stmt2: &Statement,   // statement to check
    preds: &[Predicate],                    // array of predicates
    variables: &[Variable],                 // vars from the input
    possible_values: &Vec<String>,          // set of possible values assumed by
     eval_fn: &F) -> bool
where
    F: Fn(&Predicate, &Env) -> bool,
{
    fn helper<F>(
        stmt1: &Statement, 
        stmt2: &Statement,
        env: &Env,
        variables: &[Variable],
        possible_values: &Vec<String>,
        eval_fn: &F,
    ) -> bool
    where
        F: Fn(&Predicate, &Env) -> bool,
    {
        if variables.is_empty() {
            return stmt1.eval_with_env(eval_fn, env, &[], possible_values) == stmt2.eval_with_env(eval_fn, env, &[], possible_values);
        }

        let first_var = &variables[0];
        let rest_vars = &variables[1..];

        for val in possible_values.iter() {
            let mut env_new = env.clone();
            let key = match &first_var.name {
                Some(VarName::Named(n)) => n.clone(),
                Some(VarName::Any) | None => "__any".to_string(),
            };
            env_new.insert(key, val.clone());

            if !helper(stmt1, stmt2, &env_new, rest_vars, possible_values, eval_fn) {
                return false;
            }
        }
        true
    }
    helper(stmt1, stmt2, &HashMap::new(), variables, possible_values, eval_fn)
}*/





/*
/// Check whether two statements are *semantically equivalent* under all variable assignments.
///
/// Arguments:
/// - `stmt1` and `stmt2`: the two statements to compare.
/// - `preds`: list of all predicates in scope (may be used for evaluation).
/// - `variables`: the variables whose values we want to vary to test equivalence.
/// - `eval_fn`: function to evaluate a predicate given an environment.
///
/// Returns true if `stmt1` and `stmt2` produce identical results for *all* possible
/// assignments of the variables.
 
pub fn semantically_eq<F>(stmt1: &Statement, stmt2: &Statement, preds: &[Predicate], variables: &[String], eval_fn: &F) -> bool
where
    F: Fn(&Predicate, &Env) -> bool,
{
    /// Internal recursive helper function
    /// Recursively tries all possible values for the variables to check equivalence.
    fn helper<F>(stmt1: &Statement, stmt2: &Statement, preds: &[Predicate], variables: &[String], env: &Env, eval_fn: &F) -> bool
    where
        F: Fn(&Predicate, &Env) -> bool,
    {
        // Base case: no more variables to assign,
        // simply evaluate both statements with the current environment and compare.
        if variables.is_empty() {
            return stmt1.eval_with_env(eval_fn, env, variables) == stmt2.eval_with_env(eval_fn, env, variables);
        }

        // Otherwise, take the first variable from the list:
        let first_var = &variables[0];

        // And the rest of the variables (recursive step):
        let rest_vars = &variables[1..];

        // Define possible concrete values to try for variables.
        // Customize this list as needed for your domain.
        let possible_values = vec!["v1".to_string(), "v2".to_string(), "v3".to_string()];

        // Try each possible value for the first variable:
        for val in possible_values.iter() {
            // Clone the environment and insert the new binding:
            let mut env_new = env.clone();
            env_new.insert(first_var.clone(), val.clone());

            // Recursively check equivalence for the rest of the variables with the new env.
            if !helper(stmt1, stmt2, preds, rest_vars, &env_new, eval_fn) {
                // If any assignment fails equivalence, return false immediately.
                return false;
            }
        }
        // If all assignments succeed, the statements are semantically equivalent.
        true
    }

    // Call the helper with an empty initial environment.
    helper(stmt1, stmt2, preds, variables, &HashMap::new(), eval_fn)
}




/// Method on Statement for evaluating a logical stmnt based on a function f that decides whether Predicates are T or F
/// Params:
///         - self: the logical stmnt to evaluate
///         - f   : a function that takes a Predicate and returns a boolean (T or F predicate under some assignment)
/// It recursively evaluates the logical structure of the Statement 
/* 
impl Statement {
    pub fn eval<F>(&self, f: &F) -> bool
    where
        F: Fn(&Predicate) -> bool,
    {
        match self {
            // Statement type                   Evaluation logic
            Statement::Predicate(p)     =>      f(p),
            Statement::Not(inner)       =>      !inner.eval(f),
            Statement::And(lhs, rhs)    =>      lhs.eval(f) && rhs.eval(f),
            Statement::Or(lhs, rhs)     =>      lhs.eval(f) || rhs.eval(f),
            Statement::Wildcard         =>      true, 
            Statement::Then(lhs, rhs) => lhs.eval(f) && rhs.eval(f), 
            Statement::Quantified { quant, cond, .. } => match quant {
                Quantifier::ForAll => {
                    // Simulate universal quantifier: cond must be true in all assignments
                    cond.eval(f)
                }
                Quantifier::Exists => {
                    // Simulate existential quantifier: cond must be true in at least one assignment
                    cond.eval(f)
                }
            },
        }
    }
}*/



/// Test function to check if 2 Statements are logically equivalent across all possible truth assignments of a given set of Predicates
/// Params:
///         - stmt1: first logical statement
///         - stmt2: second logical statement
///         - preds:  set of predicates (like propositional variables) involved in the stmnts
///  e.g., is stmt1 logically equivalent to stmt2 over preds?
pub fn semantically_eq(stmt1: &Statement, stmt2: &Statement, preds: &[Predicate]) -> bool {
    // let n be the #statements
    let n = preds.len(); 
    // iterate over all 2^n possible truth assignments
    for mask in 0..(1 << n) {
        // for each assignment, define a closure f: &Predicate -> bool:
        // returns true or false depending on the current assignment (determined by the bitmask)
        let f = |p: &Predicate| {
            let idx = preds.iter().position(|q| q == p).unwrap();
            (mask & (1 << idx)) != 0
        };
        // if any assignment causes them to differ, return false
        if stmt1.eval(&f) != stmt2.eval(&f) {
            return false;
        }
    }
    // if all assignments match, return true
    true
}
*/