// ast.rs
#![allow(dead_code)]
#![allow(unused_imports)]

use pest::iterators::{Pair, Pairs};
use pest_derive::Parser;


/// parser generated by Pest according to the grammar file 
/// (e.g.: CQPLParser::parse(Rule::file, input) -> parser tree (Pairs<Rule>) storing the rules
#[derive(Parser)]
#[grammar = "cqpl.pest"] // stores CQPL grammar rules
pub struct CQPLParser; 

/// schema for defining a rule
/// e.g:mem_leak.cqpl
/// _____________________
/// # mem_leak          |
/// ## domain: memory   |
/// v: *|*|*            |
/// ///                 |
/// taint_src: *@ alloc |
/// taint_snk: !drop    |
/// ____________________|
#[derive(Debug, Clone)]
pub struct RuleDef {
    pub name: Vec<String>,          // rule name (e.g.: # memory_leak)
    pub domain: Domain,             // a_mem || taint
    pub variables: Vec<Variable>,   // vars declared within the rule
    pub taint_src: Vec<Statement>,  // pre condition
    pub taint_snk: Vec<Statement>,  // post condition
}

#[derive(Debug, Clone)]
pub enum Domain { 
    Memory,     // A_mem lattice (for memory errors)
    General     // T, _|_
} 

/// variables can be expressed as follow: v_type|qualifier|name   
/// with * for any
#[derive(Debug, Clone)]
pub struct Variable {
    pub v_type: Option<Type>,           // specified var type ||*
    pub qualifier: Option<Qualifier>,   // imm||mut||*
    pub name: Option<VarName>,          // specified || *
}

#[derive(Debug, Clone)]
pub enum VarName { 
    Named(String), 
    Any
}

#[derive(Debug, Clone)]
pub enum Type { Box, Int, Float, Union, Function, Vec, Enum, Trait, Struct, Reference, Any }

#[derive(Debug, Clone)]
pub enum Qualifier { Imm, Mut, Any }

#[derive(Debug, Clone)]
pub enum Statement {
    Predicate(Predicate),
    And(Box<Statement>, Box<Statement>),
    Or(Box<Statement>, Box<Statement>),
    Not(Box<Statement>),
    Wildcard,
    Quantified { quant: Quantifier, var: String, domain: FieldDomain, cond: Box<Statement> },
}
#[derive(Debug, Clone)]
pub enum Quantifier { ForAll, Exists }

#[derive(Debug, Clone)]
pub enum FieldDomain { FieldsOf { typename: String } }

#[derive(Debug, Clone)]
pub enum Predicate {
    Alloc(Option<Term>),
    Drop(Option<Term>),
    Use(Option<Term>),
    Read(Option<Term>),
    Write(Option<Term>),
    Assign(Option<Term>),
    Custom(String, Vec<Term>),
}
#[derive(Debug, Clone)]
pub enum Term { Var(String), FieldAccess { base: String, field: String }, Literal(String) }

/// AST Builder
/// Input: result of the parser
/// recursively visits all pairs of the tree
/// Output: for each rule_item (i.e.: a rule) returns a vector of rule definition
pub fn build_ast(pairs: Pairs<Rule>) -> Vec<RuleDef> {
    let mut rules = Vec::new();
    for pair in pairs {
        match pair.as_rule() {
            Rule::file => rules.extend(build_ast(pair.into_inner())),
            Rule::rule_item => {
                let mut name = Vec::new();
                let mut domain = Domain::General;
                let mut variables = Vec::new();
                let mut taint_src = Vec::new();
                let mut taint_snk = Vec::new();

                for inner in pair.into_inner() {
                    match inner.as_rule() {
                        Rule::rule_header => name.push(inner.as_str().trim().to_string()),

                        //  *|*|*
                        Rule::var_decl => {
                            if let Some((_, pattern)) = inner.as_str().trim().split_once(':') {
                                let slots: Vec<&str> = pattern.trim().split('|').collect();

                                // 1st slot: Type
                                // using the to_lowercase returns a temporary String
                                // need to match the reference s to the temporary String, othrwise (e.g.: as_str()) may not outlive the closure
                                let v_type = match slots.get(0).map(|s| s.to_lowercase()) {
                                    Some(ref s) if *s == "box" => Some(Type::Box),
                                    Some(ref s) if *s == "int" => Some(Type::Int),
                                    Some(ref s) if *s == "float" => Some(Type::Float),
                                    Some(ref s) if *s == "union" => Some(Type::Union),
                                    Some(ref s) if *s == "function" => Some(Type::Function),
                                    Some(ref s) if *s == "vec" => Some(Type::Vec),
                                    Some(ref s) if *s == "enum" => Some(Type::Enum),
                                    Some(ref s) if *s == "trait" => Some(Type::Trait),
                                    Some(ref s) if *s == "struct" => Some(Type::Struct),
                                    Some(ref s) if *s == "reference" => Some(Type::Reference),
                                    Some(ref s) if *s == "*" || *s == "**" => Some(Type::Any),
                                    None => Some(Type::Any),
                                    _ => Some(Type::Any),
                                };

                                // 2nd slot: qualifier
                                let qualifier = match slots.get(1).map(|s| s.to_lowercase()) {
                                    Some(ref s) if *s == "imm" => Some(Qualifier::Imm),
                                    Some(ref s) if *s == "mut" => Some(Qualifier::Mut),
                                    Some(ref s) if *s == "*" => Some(Qualifier::Any),
                                    None => Some(Qualifier::Any),
                                    _ => Some(Qualifier::Any),
                                };

                                // 3rd slot: VarName 
                                // here do not lowercase the variable name since it is case sensitive
                                let var_name = match slots.get(2).map(|s| *s) {
                                    Some("*") | None => VarName::Any,
                                    Some(name) => VarName::Named(name.to_string()),
                                };

                                variables.push(Variable {
                                    name: Some(var_name),
                                    v_type,
                                    qualifier,
                                });
                            }
                        }

                        Rule::domain_decl => {
                            domain = if inner.as_str().to_lowercase().contains("memory") {
                                Domain::Memory
                            } else { Domain::General }
                        }
                      
                        Rule::taint_src_decl => {
                            for stmt in inner.into_inner() {
                                taint_src.push(parse_statement(stmt));
                            }
                        }
                        Rule::taint_snk_decl => {
                            for stmt in inner.into_inner() {
                                taint_snk.push(parse_statement(stmt));
                            }
                        }
                        _ => {}
                    }
                }

                if !name.is_empty() {
                    rules.push(RuleDef { name, domain, variables, taint_src, taint_snk });
                }
            }
            _ => {}
        }
    }
    rules
}

// Parse a single statement
fn parse_statement(pair: Pair<Rule>) -> Statement {
    match pair.as_rule() {
        Rule::primary => {
            // primary contiene un solo figlio: predicate, quant_expr, wildcard o paren_expr
            parse_statement(pair.into_inner().next().unwrap())
        }
        Rule::predicate => Statement::Predicate(parse_predicate(pair)),
        Rule::wildcard => Statement::Wildcard,
        Rule::not_expr => {
            let bang_count = pair.as_str().chars().take_while(|c| *c == '!').count();
            let inner_pair = pair.into_inner().next().unwrap();
            let mut stmt = parse_statement(inner_pair);
            for _ in 0..bang_count { stmt = Statement::Not(Box::new(stmt)); }
            stmt
        }
        Rule::quant_expr => {
            let mut inner = pair.into_inner();
            let first = inner.next().unwrap();
            match first.as_rule() {
                Rule::predicate => Statement::Predicate(parse_predicate(first)), // case *@ alloc
                Rule::ident => {
                    // case *@ var in type && predicate
                    let var = first.as_str().to_string();
                    let cond = inner.next().map(parse_statement).unwrap_or(Statement::Wildcard);
                    Statement::Quantified {
                        quant: Quantifier::ForAll,
                        var,
                        domain: FieldDomain::FieldsOf { typename: "Any".to_string() },
                        cond: Box::new(cond),
                    }
                }
                _ => panic!("Unexpected inner in quant_expr: {:?}", first.as_rule()),
            }
        }

        Rule::paren_expr | Rule::logic_expr | Rule::or_expr | Rule::and_expr => {
            parse_statement(pair.into_inner().next().unwrap())
        }
        _ => panic!("Unexpected rule in parse_statement: {:?}", pair.as_rule()),
    }
}


fn parse_predicate(pair: Pair<Rule>) -> Predicate {
    let txt = pair.as_str().trim();
    if txt.starts_with("alloc") { Predicate::Alloc(None) }
    else if txt.starts_with("drop") { Predicate::Drop(None) }
    else if txt.starts_with("use") { Predicate::Use(None) }
    else if txt.starts_with("read") { Predicate::Read(None) }
    else if txt.starts_with("write") { Predicate::Write(None) }
    else if txt.starts_with("assign") { Predicate::Assign(None) }
    else { Predicate::Custom(txt.to_string(), vec![]) }
}