// ast.rs
#![allow(dead_code)]
#![allow(unused_imports)]

use pest::iterators::{Pair, Pairs};
use pest_derive::Parser;
use serde::{Serialize, Deserialize};


/// Parser generated by Pest according to the grammar file 
/// (e.g.: CQPLParser::parse(Rule::file, input) -> parser tree (Pairs<Rule>) storing the rules
#[derive(Parser)]
#[grammar = "cqpl.pest"] // stores CQPL grammar rules
pub struct CQPLParser; 

/// schema for defining a rule
/// e.g:mem_leak.cqpl
/// _____________________
/// # mem_leak          |
/// ## domain: memory   |
/// v: *|*|*            |
///                     |
/// taint_src: *@ alloc |
/// taint_snk: !drop    |
/// ____________________|
/// 
/// Only variable name is case-sensitive
#[derive(Debug, Clone, Serialize)]
pub struct RuleDef {
    pub name: Vec<String>,          // rule name (e.g.: # memory_leak)
    pub domain: Domain,             // a_mem || taint
    pub variables: Vec<Variable>,   // vars declared within the rule
    pub taint_src: Vec<TaintBlock>, // pre condition
    pub taint_snk: Vec<TaintBlock>, // post condition
}

#[derive(Debug, Clone, Serialize)]
pub struct TaintBlock {
    pub statements: Vec<Statement>,
    pub next_op: Option<SequenceOp>, // corresponds to '|>' in input
}

// Domain to be specified in the query
#[derive(Debug, Clone, Serialize)]
pub enum Domain { 
    Memory,     // A_mem lattice (for memory errors)
    General     // T, _|_
} 

#[derive(Debug, Clone, Serialize)]
pub enum SequenceOp {
    Then,
}

/// Variables can be expressed as follow: v_type|qualifier|name   
/// with * for any
#[derive(Debug, Clone, Serialize)]
pub struct Variable {
    pub v_type: Option<Type>,           // specified var type ||*
    pub qualifier: Option<Qualifier>,   // imm||mut||*
    pub name: Option<VarName>,          // specified || *
}
/// Name of the variable to search in the query can be a soecific name or any
#[derive(Debug, Clone, Serialize)]
pub enum VarName { 
    Named(String),  // specific var name
    Any             // any variable
}
/// Type of vars to search within the pattern
#[derive(Debug, Clone, Serialize)]
pub enum Type { Box, Int, Float, Union, Function, Vec, Enum, Trait, Struct, Reference, Array, String, Tuple, Any }

/// Qualifier associated to variables 
#[derive(Debug, Clone, Serialize)]
pub enum Qualifier { Imm, Mut, Any }

/// Statements
#[derive(Debug, Clone, Serialize)]
pub enum Statement {
    Predicate(Predicate),
    And(Box<Statement>, Box<Statement>),
    Or(Box<Statement>, Box<Statement>),
    Not(Box<Statement>),
    Then(Box<Statement>, Box<Statement>), // |>
    Wildcard,
    Quantified { 
        quant: Quantifier, 
        var: Option<VarName>,  
        cond: Box<Statement> },
}
/// Quantifiers
#[derive(Debug, Clone, Serialize)]
pub enum Quantifier { 
    ForAll,     
    Exists      
}


#[derive(Debug, Clone, Serialize)]
pub enum FieldDomain { FieldsOf { typename: String } }


#[derive(Debug, Clone, Serialize)]
pub enum Predicate {
    Alloc(Option<Term>),
    Drop(Option<Term>),
    Use(Option<Term>),
    Read(Option<Term>),
    Write(Option<Term>),
    Assign(Option<Term>),
    Allocator(Option<Term>),        // to do
    InFields(Type),
    Custom(String, Vec<Term>),
}
#[derive(Debug, Clone, Serialize)]
pub enum Term { Var(String), FieldAccess { base: String, field: String }, Literal(String) }

/// AST Builder
/// Input: result of the parser
/// recursively visits all pairs of the tree
/// Output: for each rule_item (i.e.: a rule) returns a vector of rule definition
pub fn build_ast(pairs: Pairs<Rule>) -> Vec<RuleDef> {
    let mut rules = Vec::new();
    for pair in pairs {
        match pair.as_rule() {
            Rule::file => rules.extend(build_ast(pair.into_inner())),
            Rule::rule_item => {
                let mut name = Vec::new();
                let mut domain = Domain::General;
                let mut variables = Vec::new();
                let mut taint_src = Vec::new();
                let mut taint_snk = Vec::new();

                for inner in pair.into_inner() {
                    match inner.as_rule() {
                        Rule::rule_header => name.push(inner.as_str().trim().to_string()),

                        Rule::var_decl => {
                            if let Some((_, pattern)) = inner.as_str().trim().split_once(':') {
                                let slots: Vec<&str> = pattern.trim().split('|').collect();
                                let v_type = match slots.get(0).map(|s| s.to_lowercase()) {
                                    Some(ref s) if *s == "box" => Some(Type::Box),
                                    Some(ref s) if *s == "int" => Some(Type::Int),
                                    Some(ref s) if *s == "float" => Some(Type::Float),
                                    Some(ref s) if *s == "union" => Some(Type::Union),
                                    Some(ref s) if *s == "function" => Some(Type::Function),
                                    Some(ref s) if *s == "vec" || *s == "vector"  => Some(Type::Vec),
                                    Some(ref s) if *s == "enum" => Some(Type::Enum),
                                    Some(ref s) if *s == "trait" => Some(Type::Trait),
                                    Some(ref s) if *s == "struct" => Some(Type::Struct),
                                    Some(ref s) if *s == "reference" => Some(Type::Reference),
                                    Some(ref s) if *s == "array" || *s == "arr" => Some(Type::Array),
                                    Some(ref s) if *s == "string" => Some(Type::String),
                                    Some(ref s) if *s == "tuple" || *s == "tup"  => Some(Type::Tuple),

                                    Some(ref s) if *s == "*" || *s == "**" => Some(Type::Any),
                                    None => Some(Type::Any),
                                    _ => Some(Type::Any),
                                };
                                let qualifier = match slots.get(1).map(|s| s.to_lowercase()) {
                                    Some(ref s) if *s == "imm" => Some(Qualifier::Imm),
                                    Some(ref s) if *s == "mut" => Some(Qualifier::Mut),
                                    Some(ref s) if *s == "*" => Some(Qualifier::Any),
                                    None => Some(Qualifier::Any),
                                    _ => Some(Qualifier::Any),
                                };
                                let var_name = match slots.get(2).map(|s| *s) {
                                    Some("*") | None => VarName::Any,
                                    Some(name) => VarName::Named(name.to_string()),
                                };
                                variables.push(Variable {
                                    name: Some(var_name),
                                    v_type,
                                    qualifier,
                                });
                            }
                        }

                        Rule::domain_decl => {
                            domain = if inner.as_str().to_lowercase().contains("memory") {
                                Domain::Memory
                            } else { Domain::General }
                        }
                        /*  old with only 1 taint_src
                        Rule::taint_src_decl => {
                            for stmt in inner.into_inner() {
                                taint_src.push(parse_statement(stmt));
                            }
                        }*/

                        Rule::taint_src_decl => {
                            let mut inner_pairs = inner.into_inner().peekable();

                            while let Some(stmt_block) = inner_pairs.next() {
                                let statements = parse_ordered_statements(stmt_block);

                                // check if next token is a |>
                                let next_op = if let Some(_) = inner_pairs.peek() {
                                    Some(SequenceOp::Then)
                                } else {
                                    None
                                };

                                taint_src.push(TaintBlock { statements, next_op });
                            }
                        }

                       
                        Rule::taint_snk_decl => {
                            let mut inner_pairs = inner.into_inner().peekable();

                            while let Some(stmt_block) = inner_pairs.next() {
                                let statements = parse_ordered_statements(stmt_block);

                                // check if next token is a |>
                                let next_op = if inner_pairs.peek().is_some() {
                                        Some(SequenceOp::Then)
                                    } else {
                                    None
                                };

                                taint_snk.push(TaintBlock { statements, next_op });
                            }
                        }

                        _ => {}
                    }
                }

                if !name.is_empty() {
                    rules.push(RuleDef { name, domain, variables, taint_src, taint_snk });
                }
            }
            _ => {}
        }
    }
    rules
}

fn parse_ordered_statements(pair: Pair<Rule>) -> Vec<Statement> {
    pair.into_inner().map(|stmt| parse_statement(stmt)).collect()
}

// Parse a single statement
fn parse_statement(pair: Pair<Rule>) -> Statement {
    // match on the rule in the current pair (enum rule is generated by pest)
    match pair.as_rule() {
        // handle sequence_expr (if present in the grammar)
        Rule::sequence_expr => {
            // consume the pair and get an iterator on children (remove the children from the pair)
            let mut inner = pair.into_inner();
            // take the first child and recursevly handle it as a statement
            let first = parse_statement(inner.next().unwrap());
            // for each remaining child, fold creates a nested structure Then(acc, next)
            inner.fold(first, |acc, stmt| {
                // parse_statement(stmt) is the new element, Statement::Then sets acc |> new
                Statement::Then(Box::new(acc), Box::new(parse_statement(stmt)))
            })
        }

        // explicitly handle order_expr (|>) ; as above
        Rule::order_expr => {
            let mut inner = pair.into_inner();
            let first = parse_statement(inner.next().unwrap());
            inner.fold(first, |acc, stmt| {
                Statement::Then(Box::new(acc), Box::new(parse_statement(stmt)))
            })
        }
        // primary: container node having only one significant child (predicate, quant_expr, wildcard, paren_expr)
        Rule::primary => {
            
            // take that primary child and recursively parse
            parse_statement(pair.into_inner().next().unwrap())
        }
        // if pair is predicate -> construct a Statement::Predicate
        Rule::predicate => Statement::Predicate(parse_predicate(pair)),

        // wildcard * -> Statement::Wildcard
        Rule::wildcard => Statement::Wildcard,

         // not_expr: may have more ! in the head of declartion, so count them and wrap the child il figlio in #not as many #! are
        Rule::not_expr => {
            // # of ! at the very beginning of the string pair
            let bang_count = pair.as_str().chars().take_while(|c| *c == '!').count();
            // take internal child (pattern after !)
            let inner_pair = pair.into_inner().next().unwrap();
            // construct the statement of the child
            let mut stmt = parse_statement(inner_pair);
            // wrap the result into a  Statement::Not as much ! are
            for _ in 0..bang_count {
                stmt = Statement::Not(Box::new(stmt));
            }
            // return neg stmnt
            stmt
        }

        // Forall and Exists
        Rule::quant_expr => {
            // get the string pair BEFORE consuming it
            // pair.as_str() returns txt repr testuale of quant_expr,
            // store it to see if it is Forall or Exists.
            let quantifier_input_str = pair.as_str().trim().to_string();

            // consume the pair tho get the children (ident/predicate + ... )
            let mut inner = pair.into_inner();

            // determinne the quaintifier by its content
            let quantifier = if quantifier_input_str.starts_with("\\forall") {
                Quantifier::ForAll
            } else if quantifier_input_str.starts_with("\\exists") {
                Quantifier::Exists
            } else {
                panic!("Invalid quantifier. Supported: \\forall or \\exists");
            };

            // 1st child will be Rule::ident or Rule::predicate
            let first = inner.next().unwrap();

            match first.as_rule() {
                // case: \forall alloc
                Rule::predicate => {
                    let pred = parse_predicate(first);
                    Statement::Quantified {
                        quant: quantifier,
                        var: Some(VarName::Any),
                        cond: Box::new(Statement::Predicate(pred)),
                    }
                }

                // case: \exists x in Vec.fields && drop ...
                Rule::ident => {
                    let var_name = first.as_str().to_string();
                    let mut cond_parts: Vec<Statement> = Vec::new();

                    if let Some(next) = inner.next() {
                        match next.as_rule() {
                            Rule::type_access => {
                                let txt = next.as_str();
                                let (ty_str, suffix) = txt.split_once('.')
                                    .expect("type_access must be in the format Type.fields");

                                if suffix != "fields" {     
                                    panic!("error in declaring type_access: {}", txt);
                                }

                                let ty = match ty_str.to_lowercase().as_str() {
                                    "vec"    => Type::Vec,
                                    "struct" => Type::Struct,
                                    "union"  => Type::Union,
                                    "array"  => Type::Array, 
                                    "tuple"  => Type::Tuple,      
                                    other => panic!("Type '{}' is not allowed for .fields. Supported re: tuple, vec, array, struct, union", other),
                                };

                                cond_parts.push(Statement::Predicate(Predicate::InFields(ty)));

                                // se dopo c'è un predicate (&& drop, ...)
                                if let Some(maybe_pred) = inner.next() {
                                    if maybe_pred.as_rule() == Rule::predicate {
                                        cond_parts.push(Statement::Predicate(parse_predicate(maybe_pred)));
                                    }
                                }
                            }

                            Rule::predicate => {
                                cond_parts.push(Statement::Predicate(parse_predicate(next)));
                            }

                            _ => {}
                        }
                    }

                    let cond_stmt = cond_parts
                        .into_iter()
                        .reduce(|a, b| Statement::And(Box::new(a), Box::new(b)))
                        .unwrap_or(Statement::Wildcard);

                    Statement::Quantified {
                        quant: quantifier,
                        var: Some(VarName::Named(var_name)),
                        cond: Box::new(cond_stmt),
                    }
                }

                other => panic!("Unexpected inner in quant_expr: {:?}", other),
            }
        }

        Rule::paren_expr | Rule::logic_expr | Rule::or_expr | Rule::and_expr => {
            parse_statement(pair.into_inner().next().unwrap())
        }

        _ => panic!("Unexpected rule in parse_statement: {:?}", pair.as_rule()),
    }
}



fn parse_predicate(pair: Pair<Rule>) -> Predicate {
    // dont'care if lower or uppercase the pradicate for now, so to_lowercase()
    let txt = pair.as_str().trim().to_lowercase();
    match txt {
        s if s.starts_with("alloc")  => Predicate::Alloc(None),
        s if s.starts_with("drop")   => Predicate::Drop(None),
        s if s.starts_with("use")    => Predicate::Use(None),
        s if s.starts_with("read")   => Predicate::Read(None),
        s if s.starts_with("write")  => Predicate::Write(None),
        s if s.starts_with("assign") => Predicate::Assign(None),
        s if s.starts_with("allocator") => Predicate::Allocator(None),
       
        _ => Predicate::Custom(txt.to_string(), vec![]),
    }
}