WHITESPACE = _{ " " | "\t" }
NEWLINE    = _{ "\r\n" | "\n" }
COMMENT    = _{ "//" ~ (!NEWLINE ~ ANY)* }

file = { SOI ~ (rule_item ~ ("---" ~ NEWLINE)*)* ~ EOI }

rule_item = { rule_header ~ (NEWLINE* ~ rule_body_line)* ~ NEWLINE* }
rule_header = { "#" ~ (ASCII_ALPHANUMERIC | "_" )+ ~ (" " ~ (!NEWLINE ~ ANY)+ )? }

rule_body_line = _{ domain_decl | var_decl | taint_src_decl | taint_snk_decl | blank }
blank = _{ NEWLINE }

domain_decl = { "##" ~ "domain:" ~ (!NEWLINE ~ ANY)* ~ NEWLINE? }
var_decl = { "v:" ~ WHITESPACE* ~ var_pattern ~ NEWLINE? }
var_pattern = { (ASCII_ALPHANUMERIC | "_" | "*" | "|" )+ }

taint_src_decl = { "taint_src:" ~ statement_line ~ (NEWLINE* ~ "|>" ~ NEWLINE* ~ "taint_src:" ~ statement_line)* ~ NEWLINE? }
taint_snk_decl = { ("taint_snk:" | "@taint_snk:") ~ statement_line ~ (NEWLINE ~ "|>" ~ NEWLINE ~ ("taint_snk:" | "@taint_snk:") ~ statement_line )* ~ NEWLINE? }



logic_expr  = { order_expr }
order_expr  = { sequence_expr ~ ("|>" ~ sequence_expr)* }
sequence_expr = { or_expr }
or_expr     = { and_expr ~ ("||" ~ and_expr )* }
and_expr    = { not_expr ~ ("&&" ~ not_expr )* }


//not_expr    = { "!"* ~ primary }
//primary     = { predicate | quant_expr | wildcard | paren_expr }
//paren_expr  = { "(" ~ logic_expr ~ ")" }
not_expr = { "!"* ~ primary }
primary  = { predicate | wildcard | paren_expr | quant_expr }
paren_expr = { "(" ~ logic_expr ~ ")" }



wildcard    = { "*" }


quant_expr  = { ("\\forall" | "\\exists") ~ (ident | predicate) ~ ("in" ~ type_access ~ ("!=" ~ field_access)? ~ ("&&" ~ predicate)?)? }


predicate   = { ident ~ ("(" ~ arg_list? ~ ")" )? }
arg_list    = { arg ~ ("," ~ arg)* }
arg         = { field_access | ident }

type_access  = { ident ~ "." ~ "fields" }
field_access = { ident ~ "." ~ ident }


ident = @{ (ASCII_ALPHANUMERIC | "_" )+ }


ordered_statements = { statement_line ~ (NEWLINE* ~ "|>" ~ NEWLINE* ~ statement_line)* }
statement_line = { logic_expr }
