// @generated by cqpl/scripts/generate_library_effects_v1_rust.py
// DO NOT EDIT BY HAND.

use crate::structs::RustAllocationDispositionEvidenceKind;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LegacyTargetVariable { Return, None }

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LegacyDispositionProjection {
    pub summary_id: &'static str,
    pub kind: &'static str,
    pub obligation_effect: &'static str,
    pub basis: &'static str,
    pub target_variable: LegacyTargetVariable,
}

pub fn projection_for_producer_evidence(
    evidence: &RustAllocationDispositionEvidenceKind,
) -> LegacyDispositionProjection {
    match evidence {
        RustAllocationDispositionEvidenceKind::BoxFromRaw => LegacyDispositionProjection {
            summary_id: "rust_box_from_raw_v1",
            kind: "box_from_raw",
            obligation_effect: "restore_raii_obligation",
            basis: "rustc_box_from_raw_v1",
            target_variable: LegacyTargetVariable::Return,
        },
        RustAllocationDispositionEvidenceKind::BoxIntoRaw => LegacyDispositionProjection {
            summary_id: "rust_box_into_raw_v1",
            kind: "box_into_raw",
            obligation_effect: "preserve_manual_obligation",
            basis: "rustc_box_into_raw_v1",
            target_variable: LegacyTargetVariable::Return,
        },
        RustAllocationDispositionEvidenceKind::BoxLeak => LegacyDispositionProjection {
            summary_id: "rust_box_leak_v1",
            kind: "box_leak",
            obligation_effect: "preserve_persistent_obligation",
            basis: "rustc_box_leak_v1",
            target_variable: LegacyTargetVariable::Return,
        },
        RustAllocationDispositionEvidenceKind::MemDropRawPointer => LegacyDispositionProjection {
            summary_id: "rust_mem_drop_raw_pointer_v1",
            kind: "raw_pointer_drop_noop",
            obligation_effect: "no_pointee_lifecycle_effect",
            basis: "rustc_mem_drop_raw_pointer_v1",
            target_variable: LegacyTargetVariable::None,
        },
        RustAllocationDispositionEvidenceKind::MemForgetOwnedBox => LegacyDispositionProjection {
            summary_id: "rust_mem_forget_owned_box_v1",
            kind: "mem_forget_owned_box",
            obligation_effect: "preserve_unreclaimed_obligation",
            basis: "rustc_mem_forget_owned_box_v1",
            target_variable: LegacyTargetVariable::None,
        },
    }
}
