[package]
name = "ffi_extraction"
version = "0.1.0"
edition = "2021"

[dependencies]
walkdir = "2.5.0"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
cargo_metadata = "0.19.2"
thiserror = "2.0.12"
shellwords = "1.1.0"